"""Consumer Chatbot Preview router — Phase F.3.

Endpoints:
    GET    /api/chatbot                          slice for ChatbotPreviewView
    GET    /api/chatbot/conversations            list w/ filters (sentiment, escalation, search)
    GET    /api/chatbot/conversations/{id}       full transcript for a single session
    POST   /api/chatbot/seed-fixtures            populate sample fixture conversations
    DELETE /api/chatbot/fixtures                 wipe seeded fixture rows

Read-only from the dashboard side. Conversation rows are generated by the
real consumer-facing chatbot (out of scope for this demo — rows are seeded
fixture-style so the dashboard surface has something to render).

Tier gating: dashboard hides the sidebar tab for tier < 3, but the endpoints
still return data so the upsell card can show the empty-state preview. The
real (downstream) chatbot enforces its own per-tier gating.
"""
from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any, Literal, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from ..db import get_db
from ..models import Business, ChatbotConversation

router = APIRouter()


SENTIMENT_LABELS: dict[str, str] = {
    "positive": "Positive",
    "neutral":  "Neutral",
    "negative": "Negative",
    "mixed":    "Mixed",
}


# ---------------------------------------------------------------------------
# Payload shapers
# ---------------------------------------------------------------------------

def conversation_summary(c: ChatbotConversation) -> dict[str, Any]:
    """List-card payload — omits the full transcript (which can be long)."""
    return {
        "id":              c.id,
        "externalId":      c.external_id,
        "consumerLabel":   c.consumer_label,
        "topicLabel":      c.topic_label,
        "sentiment":       c.sentiment,
        "sentimentLabel":  SENTIMENT_LABELS.get(c.sentiment, c.sentiment),
        "escalationFlag":  c.escalation_flag,
        "escalationReason": c.escalation_reason,
        "turnCount":       c.turn_count,
        "durationSeconds": c.duration_seconds,
        "startedAt":       c.started_at.isoformat() if c.started_at else None,
        "endedAt":         c.ended_at.isoformat() if c.ended_at else None,
        "referrerLabel":   c.referrer_label,
    }


def conversation_full(c: ChatbotConversation) -> dict[str, Any]:
    """Detail payload — includes the transcript."""
    return {
        **conversation_summary(c),
        "transcript": c.transcript_json or [],
    }


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/chatbot")
def get_chatbot(business_id: int = 1, db: Session = Depends(get_db)) -> dict[str, Any]:
    biz = db.get(Business, business_id)
    if biz is None:
        raise HTTPException(status_code=404, detail=f"business {business_id} not found")

    conversations = (
        db.query(ChatbotConversation)
        .filter(ChatbotConversation.business_id == business_id)
        .order_by(ChatbotConversation.started_at.desc(), ChatbotConversation.id.desc())
        .limit(50)
        .all()
    )

    total          = len(conversations)
    escalation_ct  = sum(1 for c in conversations if c.escalation_flag)
    sentiment_ct: dict[str, int] = {"positive": 0, "neutral": 0, "negative": 0, "mixed": 0}
    for c in conversations:
        sentiment_ct[c.sentiment] = sentiment_ct.get(c.sentiment, 0) + 1
    avg_turns      = (sum(c.turn_count for c in conversations) / total) if total else 0.0
    avg_duration_s = (sum(c.duration_seconds for c in conversations) / total) if total else 0.0

    # Top recurring topic labels (frequency-sorted, top 6). Topic strings are
    # already short headlines per session so a string-equality groupby works
    # without LLM clustering. When the real chatbot is wired, we can replace
    # this with a proper topic-clustering pipeline.
    topic_counts: dict[str, int] = {}
    for c in conversations:
        topic_counts[c.topic_label] = topic_counts.get(c.topic_label, 0) + 1
    top_topics = sorted(
        [{"label": k, "count": v} for k, v in topic_counts.items()],
        key=lambda t: t["count"],
        reverse=True,
    )[:6]

    return {
        "tier":              biz.tier,
        "tierEligible":      biz.tier >= 3,
        "conversations":     [conversation_summary(c) for c in conversations],
        "totals": {
            "count":            total,
            "escalationCount":  escalation_ct,
            "sentimentCounts":  sentiment_ct,
            "avgTurns":         avg_turns,
            "avgDurationSecs":  avg_duration_s,
        },
        "topTopics":        top_topics,
        "hasAnyConversation": total > 0,
    }


@router.get("/chatbot/conversations")
def list_conversations(
    business_id: int = 1,
    sentiment: Optional[str] = Query(None, description="positive|neutral|negative|mixed"),
    escalation_only: bool = Query(False),
    search: Optional[str] = Query(None, max_length=200),
    limit: int = Query(50, ge=1, le=200),
    db: Session = Depends(get_db),
) -> list[dict[str, Any]]:
    q = db.query(ChatbotConversation).filter(ChatbotConversation.business_id == business_id)
    if sentiment:
        q = q.filter(ChatbotConversation.sentiment == sentiment)
    if escalation_only:
        q = q.filter(ChatbotConversation.escalation_flag.is_(True))
    if search:
        q = q.filter(ChatbotConversation.topic_label.ilike(f"%{search}%"))
    rows = (
        q.order_by(ChatbotConversation.started_at.desc(), ChatbotConversation.id.desc())
        .limit(limit)
        .all()
    )
    return [conversation_summary(c) for c in rows]


@router.get("/chatbot/conversations/{conversation_id}")
def get_conversation(
    conversation_id: int,
    business_id: int = 1,
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    c = db.get(ChatbotConversation, conversation_id)
    if c is None or c.business_id != business_id:
        raise HTTPException(status_code=404, detail=f"conversation {conversation_id} not found")
    return conversation_full(c)


# ---------------------------------------------------------------------------
# Fixture seeder — demo affordance for sales walkthroughs
# ---------------------------------------------------------------------------
#
# Trevor (or a sales rep) can populate ~10 sample conversations in one click
# from the dashboard's empty-state CTA. These are publisher-prospects asking
# Quadd.ai's consumer-facing chatbot about features — the actual use case
# Quadd's chatbot serves. Mirrors the /api/inventory/import-fixture pattern.

_QUADD_FIXTURES = [
    # (topic, sentiment, escalation, escalation_reason, transcript, referrer, duration_s)
    (
        "How does Universal Document Extractor work?",
        "positive", False, None,
        [
            ("consumer", "Hi — I'm a publisher in southwest Minnesota. Does your document extractor handle court filings as a PDF input?"),
            ("bot", "Yes — PDF is the most common input. The extractor parses court documents (criminal, civil, family) and returns formatted copy in your publication's house style. Most publishers report 2–3 hours saved per writer per week."),
            ("consumer", "What about scanned PDFs vs digital ones?"),
            ("bot", "Both work. Digital PDFs are faster (no OCR step); scanned PDFs pass through an OCR layer first. Same output format either way."),
            ("consumer", "Can I try it with one of my actual court docs before subscribing?"),
            ("bot", "Yes — the 7-day free trial includes the full Universal Document Extractor. No credit card required to start. Upload your PDF and you'll see the formatted output in under a minute."),
            ("consumer", "Great, I'll sign up."),
        ],
        "quadd.ai homepage", 215,
    ),
    (
        "Pricing for a small weekly paper",
        "positive", False, None,
        [
            ("consumer", "I run a single weekly paper — staff of three. What does it cost?"),
            ("bot", "Quadd.ai is a flat $99/month for the full bundle: Universal Document Extractor, AP-Style Checker, and Interview Transcription. That includes unlimited usage for up to 5 newsroom seats."),
            ("consumer", "Any discount for small papers?"),
            ("bot", "The single price was set with small papers specifically in mind — no per-seat upcharge, no per-document fees. If you'd like to talk about a year-up-front discount, I can connect you to Trevor."),
            ("consumer", "That works for me at $99. Let me try the trial."),
        ],
        "Publisher Association directory", 142,
    ),
    (
        "AP Style proofer accuracy?",
        "neutral", False, None,
        [
            ("consumer", "How accurate is the AP Style proofer compared to a human copy editor?"),
            ("bot", "It catches roughly 85–90% of AP-style issues a copy editor would flag — comma usage, number formatting, capitalization, datelines, attribution patterns. It doesn't replace the human pass; it shortens it. Most newsrooms report a 40–60% reduction in copy-edit time."),
            ("consumer", "What's a typical false-positive rate?"),
            ("bot", "About 5–8%. Usually those involve intentional house-style deviations from AP. The proofer learns your overrides — you mark one as 'we do it this way' and it stops flagging that pattern."),
            ("consumer", "OK — useful to know it's an assist, not a replacement."),
        ],
        "quadd.ai/features", 168,
    ),
    (
        "Multi-paper group support?",
        "positive", True, "Lead with 7 papers — high-value prospect, deserves owner outreach",
        [
            ("consumer", "Our group runs 7 weekly papers across the same county. Can Quadd handle that, and can each paper have its own house style?"),
            ("bot", "Yes — you can register multiple publications under one account, and the AP-Style Checker learns each paper's house-style overrides independently. Universal Document Extractor uses per-paper templates."),
            ("consumer", "Pricing for 7 papers?"),
            ("bot", "For multi-paper groups we have a per-publication discount. Let me connect you to Trevor — he handles group pricing directly so you get something tailored to your scale."),
            ("consumer", "Yes, please. I'll watch for his outreach."),
        ],
        "Industry trade group referral", 124,
    ),
    (
        "Interview transcription — local accents?",
        "neutral", False, None,
        [
            ("consumer", "Does the transcription handle southern Minnesota / Iowa accents well? Most tools I've tried garble names."),
            ("bot", "The transcription engine is tuned for North American English including regional accents. For proper-noun accuracy (names, town names, business names) you can pre-load a custom vocabulary per interview — about 30 seconds of setup. Most users report >95% accuracy with custom vocab loaded."),
            ("consumer", "And it diarizes speakers?"),
            ("bot", "Yes — speaker labels for up to 6 voices. After the transcript you can rename Speaker 1, Speaker 2, etc., to the actual names. Quotes pull cleanly from there."),
        ],
        "quadd.ai blog → feature post", 191,
    ),
    (
        "Integration with InDesign / NewsCycle?",
        "mixed", True, "User asked about InDesign export — feature exists but isn't documented well; surface to product",
        [
            ("consumer", "Does the document extractor output land directly in InDesign? Or do I have to copy/paste?"),
            ("bot", "Right now the output is text + structured metadata (headlines, body, captions) that you copy in. InDesign tagged-text export is on the roadmap but not shipped yet."),
            ("consumer", "What about NewsCycle / NewsEdit?"),
            ("bot", "We don't have a native NewsCycle integration yet — most users paste from the web interface. If NewsCycle integration is a blocker for you, let me flag it for the product team."),
            ("consumer", "It's not a blocker but it would be nice. Worth flagging."),
        ],
        "quadd.ai/integrations", 156,
    ),
    (
        "Refund / cancellation policy?",
        "neutral", False, None,
        [
            ("consumer", "If I subscribe and it doesn't work for our workflow, can I cancel? Refund?"),
            ("bot", "Yes — month-to-month, cancel any time from your account settings. We also pro-rate refunds within the first 14 days, no questions asked. The 7-day free trial means you have time to validate fit before any charge."),
        ],
        "quadd.ai pricing page", 47,
    ),
    (
        "How is this different from ChatGPT?",
        "positive", False, None,
        [
            ("consumer", "Honestly — why pay you when ChatGPT is free?"),
            ("bot", "Fair question. ChatGPT is a generalist chatbot; Quadd.ai is purpose-built for newsroom workflows. Three concrete differences: (1) Universal Document Extractor handles long court docs that ChatGPT chokes on — try a 38-page filing in each; (2) AP-Style Checker is tuned to AP house rules and learns your overrides; (3) Interview Transcription has speaker diarization + per-interview custom vocab. ChatGPT can do bits of each, but you'd be stitching them together."),
            ("consumer", "What about the document length issue?"),
            ("bot", "Quadd's extractor handles court filings up to 200 pages in a single pass. ChatGPT's context window means anything over ~30 pages requires manual chunking, and the formatted output quality degrades."),
            ("consumer", "OK — that's the differentiation I needed."),
        ],
        "Reddit r/Journalism thread", 198,
    ),
    (
        "Bulk pricing for a journalism school?",
        "positive", True, "Journalism program lead — 80 students, potentially institutional license",
        [
            ("consumer", "I run a journalism program at a state university — about 80 students. Is there an academic license?"),
            ("bot", "We have an institutional academic license — student seats are heavily discounted. Let me connect you to Trevor directly so he can walk you through the program."),
            ("consumer", "Great — what's the best way to reach him?"),
            ("bot", "I'll flag your conversation for owner outreach — Trevor will reach out by email within 1 business day. Could you confirm your email?"),
            ("consumer", "trevor.b.contact@university.edu — though I'd love to see the pricing now if possible."),
            ("bot", "Owner outreach noted. In the meantime, the per-student academic seat is $4/month with a minimum of 50 seats."),
        ],
        "EDU listserv", 261,
    ),
    (
        "Data privacy — where are documents stored?",
        "positive", False, None,
        [
            ("consumer", "If I upload sensitive court documents, where do they live? Are they used to train models?"),
            ("bot", "Documents are stored in US-region encrypted storage (AES-256 at rest). They are NEVER used to train any underlying model — your content stays your content. Per-publication isolation means another paper's data is never accessible to yours. Retention is 30 days by default; you can configure shorter."),
            ("consumer", "And human review?"),
            ("bot", "No human at Quadd reviews your documents. Customer-support cases require explicit per-incident permission before a support engineer sees any document content."),
            ("consumer", "Perfect — that's what I needed to hear."),
        ],
        "quadd.ai security page", 142,
    ),
]


@router.post("/chatbot/seed-fixtures")
def seed_fixtures(business_id: int = 1, db: Session = Depends(get_db)) -> dict[str, Any]:
    """Populate fixture conversations so the dashboard has something to show.

    Sales-rep affordance — clicking the empty-state CTA imports ~10 sample
    publisher-prospect conversations. Idempotent: re-running clears the
    existing fixture rows (external_id LIKE 'fixture-%') and re-imports.
    """
    biz = db.get(Business, business_id)
    if biz is None:
        raise HTTPException(status_code=404, detail=f"business {business_id} not found")

    # Wipe prior fixtures (external_id starts with 'fixture-').
    db.query(ChatbotConversation).filter(
        ChatbotConversation.business_id == business_id,
        ChatbotConversation.external_id.like("fixture-%"),
    ).delete(synchronize_session=False)

    now = datetime.utcnow()
    created = 0
    for idx, (topic, sentiment, escalation, reason, transcript, referrer, duration_s) in enumerate(_QUADD_FIXTURES):
        # Spread sessions across the last 14 days, most recent first.
        started_at = now - timedelta(days=idx, hours=(idx * 3) % 24, minutes=(idx * 17) % 60)
        ended_at = started_at + timedelta(seconds=duration_s)
        turns_json = [
            {"who": who, "text": text, "at": (started_at + timedelta(seconds=int(duration_s * (i + 1) / (len(transcript) + 1)))).isoformat()}
            for i, (who, text) in enumerate(transcript)
        ]
        db.add(ChatbotConversation(
            business_id=business_id,
            external_id=f"fixture-{idx + 1}",
            consumer_label=f"anonymous · {('iPhone Safari', 'desktop Chrome', 'Android Chrome', 'desktop Firefox')[idx % 4]}",
            topic_label=topic,
            transcript_json=turns_json,
            sentiment=sentiment,
            escalation_flag=escalation,
            escalation_reason=reason,
            turn_count=len(transcript),
            duration_seconds=duration_s,
            started_at=started_at,
            ended_at=ended_at,
            referrer_label=referrer,
        ))
        created += 1

    db.commit()
    return {"ok": True, "createdCount": created}


@router.delete("/chatbot/fixtures")
def clear_fixtures(business_id: int = 1, db: Session = Depends(get_db)) -> dict[str, Any]:
    """Wipe seeded fixture conversations. Real conversations untouched."""
    removed = (
        db.query(ChatbotConversation)
        .filter(
            ChatbotConversation.business_id == business_id,
            ChatbotConversation.external_id.like("fixture-%"),
        )
        .delete(synchronize_session=False)
    )
    db.commit()
    return {"ok": True, "removedCount": removed}
