"""Business user authentication and invite system for Main Street OS.

Two tables managed here:
  - business_users: active accounts with bcrypt password hashes
  - business_invites: publisher-scoped invite codes generated by admins

Session auth uses itsdangerous-signed cookies; never trust URL parameters
for org_id — always derive it from the validated session payload.
"""

import logging
import os
import secrets as _secrets
from datetime import datetime

import bcrypt
from fastapi import Request
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer

from src.core.database import get_connection

logger = logging.getLogger(__name__)

# ── Session config ──────────────────────────────────────────────────
COOKIE_NAME = "biz_session"
MAX_AGE = 60 * 60 * 24 * 7  # 7 days

_secret = os.getenv("BUSINESS_SESSION_SECRET", "dev-secret-change-me")
if _secret == "dev-secret-change-me":
    logger.warning("BUSINESS_SESSION_SECRET not set — using insecure default")
_serializer = URLSafeTimedSerializer(_secret)


# ── Table init ──────────────────────────────────────────────────────
def init_tables() -> None:
    """Create business_users and business_invites tables (idempotent)."""
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS business_users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            organization_id INTEGER NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            name TEXT NOT NULL,
            role TEXT DEFAULT 'owner',
            is_active INTEGER DEFAULT 1,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            last_login TEXT,
            FOREIGN KEY (organization_id) REFERENCES organizations(id)
        )
    """)
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS idx_biz_users_email ON business_users(email)"
    )
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS idx_biz_users_org ON business_users(organization_id)"
    )

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS business_invites (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            invite_code TEXT UNIQUE NOT NULL,
            business_name TEXT,
            publisher TEXT NOT NULL,
            tier TEXT DEFAULT 'growth',
            note TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            used_at TEXT,
            used_by_user_id INTEGER
        )
    """)
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS idx_invite_code ON business_invites(invite_code)"
    )
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS idx_invite_publisher ON business_invites(publisher)"
    )

    conn.commit()
    conn.close()
    logger.info("business_users + business_invites tables ready")


# ── Password helpers ────────────────────────────────────────────────
def hash_password(plain: str) -> str:
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


def verify_password(plain: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(plain.encode(), hashed.encode())
    except Exception:
        return False


# ── Business user CRUD ──────────────────────────────────────────────
def create_business_user(
    email: str,
    password: str,
    name: str,
    organization_id: int,
    role: str = "owner",
) -> int:
    """Create a business user. Returns the new user id."""
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO business_users (organization_id, email, password_hash, name, role) "
        "VALUES (?, ?, ?, ?, ?)",
        (organization_id, email.lower().strip(), hash_password(password), name, role),
    )
    conn.commit()
    user_id = cursor.lastrowid
    conn.close()
    logger.info("Created business user %s for org %s", email, organization_id)
    return user_id


def get_user_by_email(email: str) -> dict | None:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT * FROM business_users WHERE email = ? AND is_active = 1",
        (email.lower().strip(),),
    )
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def get_user_by_id(user_id: int) -> dict | None:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT * FROM business_users WHERE id = ? AND is_active = 1",
        (user_id,),
    )
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def update_last_login(user_id: int) -> None:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE business_users SET last_login = ? WHERE id = ?",
        (datetime.now().isoformat(), user_id),
    )
    conn.commit()
    conn.close()


# ── Invite CRUD ─────────────────────────────────────────────────────
def create_invite(
    business_name: str, publisher: str, tier: str = "growth", note: str = ""
) -> str:
    """Create an invite and return the invite code."""
    code = _secrets.token_urlsafe(16)
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO business_invites (invite_code, business_name, publisher, tier, note) "
        "VALUES (?, ?, ?, ?, ?)",
        (code, business_name, publisher, tier, note),
    )
    conn.commit()
    conn.close()
    logger.info(
        "Created invite for %s under %s (tier=%s)", business_name, publisher, tier
    )
    return code


def get_invite(code: str) -> dict | None:
    """Look up an invite by code. Returns dict or None."""
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM business_invites WHERE invite_code = ?", (code,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def get_invites_for_publisher(publisher: str | None = None) -> list[dict]:
    """List invites for a publisher. If None, returns all (network-wide)."""
    conn = get_connection()
    cursor = conn.cursor()
    if publisher:
        cursor.execute(
            "SELECT * FROM business_invites WHERE publisher = ? ORDER BY created_at DESC",
            (publisher,),
        )
    else:
        cursor.execute("SELECT * FROM business_invites ORDER BY created_at DESC")
    rows = [dict(r) for r in cursor.fetchall()]
    conn.close()
    return rows


def mark_invite_used(code: str, user_id: int) -> None:
    """Mark an invite as used."""
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE business_invites SET used_at = ?, used_by_user_id = ? "
        "WHERE invite_code = ?",
        (datetime.now().isoformat(), user_id, code),
    )
    conn.commit()
    conn.close()


# ── Session management ──────────────────────────────────────────────
def create_session(user: dict) -> str:
    """Return a signed session token for the given user."""
    return _serializer.dumps(
        {
            "user_id": user["id"],
            "org_id": user["organization_id"],
            "email": user["email"],
        }
    )


def decode_session(token: str) -> dict | None:
    """Decode a session token. Returns payload dict or None."""
    try:
        return _serializer.loads(token, max_age=MAX_AGE)
    except (BadSignature, SignatureExpired):
        return None


def get_current_user(request: Request) -> dict | None:
    """Read session cookie → look up user. Returns user dict or None."""
    token = request.cookies.get(COOKIE_NAME)
    if not token:
        return None
    payload = decode_session(token)
    if not payload:
        return None
    return get_user_by_id(payload["user_id"])


class AuthRequired(Exception):
    """Raised when a route requires authentication but no valid session exists."""


async def require_auth(request: Request) -> dict:
    """FastAPI dependency — returns user dict or raises AuthRequired."""
    user = get_current_user(request)
    if not user:
        raise AuthRequired()
    return user
