"""Generate worker.js with the two legal pages embedded as base64.

Why base64: the legal HTML contains typographic punctuation (em-dashes, curly
quotes) and could contain backticks / ${...}; base64 sidesteps every escaping
hazard and round-trips UTF-8 byte-exactly. The Worker decodes base64 → raw
bytes → Response, and the charset=utf-8 header does the rest.

Run:  uv run python deploy/cloudflare-worker/build-worker.py
(re-run whenever amplafai-privacy.html / amplafai-terms.html change)
"""
from __future__ import annotations

import base64
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEPLOY = HERE.parent

SOURCES = {
    "/privacy": DEPLOY / "amplafai-privacy.html",
    "/terms": DEPLOY / "amplafai-terms.html",
}


def main() -> None:
    entries = []
    for path, src in SOURCES.items():
        b64 = base64.b64encode(src.read_bytes()).decode("ascii")
        entries.append(f'  "{path}": "{b64}",')
    pages_block = "\n".join(entries)

    worker = f"""// AUTO-GENERATED by build-worker.py — edit the source HTML, not this file.
//
// Serves amplafai.com/privacy and amplafai.com/terms from Cloudflare's edge,
// in front of the GoDaddy (Airo) homepage. Routes (see wrangler.toml) scope
// this Worker to ONLY those two paths, so the homepage and everything else
// pass straight through to GoDaddy untouched.

const PAGES = {{
{pages_block}
}};

function bytesFromBase64(b64) {{
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}}

export default {{
  async fetch(request) {{
    const url = new URL(request.url);
    // Normalize: strip a trailing slash so /privacy and /privacy/ both match.
    let path = url.pathname.replace(/\\/+$/, "");
    if (path === "") path = "/";

    const b64 = PAGES[path];
    if (b64) {{
      return new Response(bytesFromBase64(b64), {{
        headers: {{
          "content-type": "text/html; charset=utf-8",
          "cache-control": "public, max-age=3600",
          "x-served-by": "amplafai-legal-worker",
        }},
      }});
    }}

    // Defensive passthrough — shouldn't be reached given the scoped routes,
    // but if it is, hand the request to the GoDaddy origin unchanged.
    return fetch(request);
  }},
}};
"""

    out = HERE / "worker.js"
    out.write_text(worker, encoding="utf-8")
    total = sum(len(s.read_bytes()) for s in SOURCES.values())
    print(f"wrote {out} ({out.stat().st_size} bytes; {total} bytes of HTML embedded)")


if __name__ == "__main__":
    main()
